const ACTIONS = {
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  SHARE_ROOMS: 'SHARE_ROOMS',
  ADD_PEER: 'ADD_PEER',
  REMOVE_PEER: 'REMOVE_PEER',
  RELAY_SDP: 'RELAY_SDP',
  RELAY_ICE: 'RELAY_ICE',
  ICE_CANDIDATE: 'ICE_CANDIDATE',
  SESSION_DESCRIPTION: 'SESSION_DESCRIPTION',
};

module.exports = ACTIONS;
